// Sample data for `npm run dev` only -- release builds load the JSON
// injected by render_html() and this module gets tree-shaken away.
import type { ReportData } from '../shared/types';

export const devFixture: ReportData = {
  suiteName: 'pyrunner dev fixture',
  dimensions: ['module', 'suite', 'owner'],
  generatedAt: new Date().toISOString(),
  totalDuration: 74.2,
  runStartedAt: 1700000000,
  runDuration: 5.5,
  numWorkers: 3,
  coverage: { percent: 83.4, htmlDir: 'reports/coverage/html' },
  tests: [
    {
      id: 'examples/test_login.py::test_valid_login',
      caseId: 'C1001',
      tags: ['smoke', 'auth'],
      outcome: 'passed',
      duration: 1.234,
      attempts: 1,
      error: null,
      artifacts: [],
      steps: [
        { name: 'open login page', outcome: 'passed', duration: 0.4 },
        {
          name: 'submit credentials',
          outcome: 'passed',
          duration: 0.6,
          children: [{ name: 'wait for redirect', outcome: 'passed', duration: 0.3 }],
        },
      ],
      properties: { browser: 'chromium' },
      groups: { module: 'examples.test_login', suite: 'auth', owner: 'alice' },
      quarantined: false,
      quarantineReason: null,
      nearTimeout: false,
      workerRestartOverhead: null,
      assertDetails: null,
      logs: [],
      workerId: 1,
      startedAt: 1700000000.2,
      flaky: false,
    },
    {
      id: 'examples/test_login.py::test_invalid_password[param-1]',
      caseId: 'C1002',
      tags: ['auth', 'negative'],
      outcome: 'failed',
      duration: 4.51,
      attempts: 2,
      error:
        'Traceback (most recent call last):\n  File "examples/test_login.py", line 42, in test_invalid_password\n    assert response.status == 403\nAssertionError',
      artifacts: [
        { label: 'screenshot.png', href: 'artifacts/attempt-1/screenshot.png', embedded: false },
        { label: 'trace.zip', href: 'artifacts/attempt-1/trace.zip', embedded: false },
      ],
      steps: [
        { name: 'open login page', outcome: 'passed', duration: 0.5 },
        {
          name: 'submit bad credentials',
          outcome: 'failed',
          duration: 3.9,
          error: 'expected 403, got 200',
        },
      ],
      properties: {},
      groups: { module: 'examples.test_login', suite: 'auth', owner: 'bob' },
      quarantined: false,
      quarantineReason: null,
      nearTimeout: true,
      workerRestartOverhead: null,
      assertDetails: {
        expr: 'response.status == 403',
        op: '==',
        left: { repr: '200', type: 'int' },
        right: { repr: '403', type: 'int' },
        names: { 'response.status': '200' },
      },
      logs: [
        {
          attempt: 1,
          stdout: 'starting login flow\n',
          stderr: '',
          records: [{ level: 'WARNING', name: 'auth', message: 'unexpected 200' }],
        },
        {
          attempt: 2,
          stdout: 'starting login flow (retry)\n',
          stderr: 'connection reset\n',
          records: [],
          truncated: true,
        },
      ],
      workerId: 1,
      startedAt: 1700000001.6,
      flaky: true,
    },
    {
      id: 'examples/test_search.py::test_search_smoke',
      caseId: null,
      tags: ['smoke', 'search'],
      outcome: 'quarantined_failure',
      duration: 2.1,
      attempts: 1,
      error: 'TimeoutError: results pane did not load',
      artifacts: [],
      steps: [],
      properties: {},
      groups: { module: 'examples.test_search', suite: 'search', owner: 'alice' },
      quarantined: true,
      quarantineReason: 'flaky on CI, see BUG-77',
      nearTimeout: false,
      workerRestartOverhead: null,
      assertDetails: null,
      logs: [],
      workerId: 2,
      startedAt: 1700000000.5,
      flaky: false,
    },
    {
      id: 'examples/test_search.py::test_pagination',
      caseId: 'C2001',
      tags: ['search'],
      outcome: 'skipped',
      duration: 0,
      attempts: 1,
      error: null,
      artifacts: [],
      steps: [],
      properties: {},
      groups: { module: 'examples.test_search', suite: 'search', owner: 'bob' },
      quarantined: false,
      quarantineReason: null,
      nearTimeout: false,
      workerRestartOverhead: null,
      assertDetails: null,
      logs: [],
      workerId: 2,
      startedAt: 1700000002.9,
      flaky: false,
    },
    {
      id: 'examples/test_export.py::test_export_pdf',
      caseId: 'C3001',
      tags: ['export'],
      outcome: 'expected_failure',
      duration: 0.8,
      attempts: 1,
      error: null,
      artifacts: [],
      steps: [],
      properties: {},
      groups: { module: 'examples.test_export', suite: 'export', owner: 'alice' },
      quarantined: false,
      quarantineReason: null,
      nearTimeout: false,
      workerRestartOverhead: null,
      assertDetails: null,
      logs: [],
      workerId: 3,
      startedAt: 1700000000.1,
      flaky: false,
    },
  ],
};
