"""
pyproject.toml -> ctrlrunner.toml migration (config companion to the
source-file passes).

Reads [tool.pytest.ini_options] from the pyproject.toml governing the
migrated paths and generates a ctrlrunner.toml next to it:

    markers = ["name: desc", ...]   -> registered_tags = [...] (descriptions
                                       stripped; the case-id marker and
                                       markers the source migration converts
                                       away are excluded)
    addopts --strict-markers        -> strict_tags = true
    addopts -n N / --numprocesses N -> num_workers = N ("auto" kept as string)
    testpaths = [...]               -> root = "<first>" (multiple -> TODO)
    timeout = N (pytest-timeout)    -> timeout = N

Everything unmappable (filterwarnings, pythonpath, asyncio_*, other
addopts flags, unknown ini keys) is emitted as commented TODO lines in
the generated file, so nothing silently disappears. An existing
ctrlrunner.toml is never touched.
"""

import json
import shlex
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    import tomllib
else:
    try:
        import tomllib  # Python 3.11+
    except ImportError:  # pragma: no cover
        tomllib = None

TODO_COMMENT = "# TODO(ctrlrunner-migrate): "

# Markers the source migration converts to something other than a tag --
# registering them as tags would be wrong or useless.
_CONVERTED_MARKERS = {
    "timeout",
    "flaky",
    "asyncio",
    "skip",
    "skipif",
    "xfail",
    "usefixtures",
    "parametrize",
}

HEADER = "# generated by ctrlrunner.migrate from pyproject.toml -- review before use\n"


@dataclass
class ConfigMigration:
    source: Path  # the pyproject.toml read
    target: Path  # sibling ctrlrunner.toml
    text: str | None  # generated toml, None when skipped
    skipped_reason: str | None = None
    notes: list[str] = field(default_factory=list)  # unmappable options
    mapped: int = 0  # number of options that got a ctrlrunner.toml key


def find_pyproject(paths) -> Path | None:
    """First pyproject.toml with a [tool.pytest.ini_options] table found
    walking upward from each input path (stops at a .git dir boundary or
    the filesystem root) -- handles the common "migrate tests/, config
    at repo root" layout."""
    if tomllib is None:  # pragma: no cover
        return None
    for raw in paths:
        directory = Path(raw).resolve()
        if not directory.is_dir():
            directory = directory.parent
        while True:
            candidate = directory / "pyproject.toml"
            if candidate.is_file():
                try:
                    data = tomllib.loads(candidate.read_text(encoding="utf-8"))
                except (OSError, tomllib.TOMLDecodeError):
                    data = {}
                if data.get("tool", {}).get("pytest", {}).get("ini_options"):
                    return candidate
            if (directory / ".git").exists() or directory.parent == directory:
                break
            directory = directory.parent
    return None


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return json.dumps(str(value))  # valid TOML basic string


def _parse_addopts(addopts) -> list[str]:
    if isinstance(addopts, str):
        return shlex.split(addopts)
    return [str(t) for t in (addopts or [])]


def _map_addopts(tokens: list[str], out: dict[str, Any], notes: list[str]):
    i = 0
    while i < len(tokens):
        token = tokens[i]
        if token == "--strict-markers":
            out["strict_tags"] = True
        elif token in ("-n", "--numprocesses") and i + 1 < len(tokens):
            out["num_workers"] = _workers_value(tokens[i + 1])
            i += 1
        elif token.startswith(("-n=", "--numprocesses=")):
            out["num_workers"] = _workers_value(token.split("=", 1)[1])
        else:
            notes.append(f"addopts '{token}' has no ctrlrunner.toml equivalent")
        i += 1


def _workers_value(raw: str):
    if raw == "auto":
        return "auto"
    try:
        return int(raw)
    except ValueError:
        return raw


def _marker_names(markers, case_id_marker: str) -> list[str]:
    names = []
    excluded = _CONVERTED_MARKERS | ({case_id_marker} if case_id_marker else set())
    for entry in markers or []:
        name = str(entry).split(":", 1)[0].strip()
        if name and name not in excluded and name not in names:
            names.append(name)
    return names


def _prefix_hint(names: list[str]) -> str | None:
    """A tip comment when >=3 tags share an underscore prefix -- the user
    may prefer a single "family_*" pattern in registered_tags."""
    prefixes: dict[str, int] = {}
    for name in names:
        head, sep, _ = name.partition("_")
        if sep:
            prefixes[head] = prefixes.get(head, 0) + 1
    families = sorted(f"{p}_*" for p, n in prefixes.items() if n >= 3)
    if not families:
        return None
    return f"# tip: families like {', '.join(families)} can be collapsed to prefix patterns"


def build_ctrlrunner_toml(ini_options: dict, case_id_marker: str) -> tuple[str, list[str], int]:
    """Returns (generated toml text, unmappable-option notes, mapped count)."""
    notes: list[str] = []
    out: dict[str, Any] = {}

    if "testpaths" in ini_options:
        testpaths = ini_options["testpaths"]
        if isinstance(testpaths, str):
            testpaths = [testpaths]
        if testpaths:
            out["root"] = testpaths[0]
            if len(testpaths) > 1:
                notes.append(
                    f"multiple testpaths ({', '.join(map(str, testpaths))}) -- "
                    f"ctrlrunner root is a single directory; kept the first"
                )

    if "timeout" in ini_options:
        out["timeout"] = ini_options["timeout"]

    _map_addopts(_parse_addopts(ini_options.get("addopts")), out, notes)

    tag_names = _marker_names(ini_options.get("markers"), case_id_marker)

    handled = {"testpaths", "timeout", "addopts", "markers"}
    for key, value in ini_options.items():
        if key in handled:
            continue
        notes.append(f"pytest ini option '{key} = {value!r}' has no ctrlrunner.toml equivalent")

    lines = [HEADER, "\n[ctrlrunner]\n"]
    for key in ("root", "timeout", "num_workers", "strict_tags"):
        if key in out:
            lines.append(f"{key} = {_toml_value(out[key])}\n")
    mapped = len(out)
    if tag_names:
        lines.append("registered_tags = [\n")
        lines.extend(f"    {json.dumps(name)},\n" for name in tag_names)
        lines.append("]\n")
        hint = _prefix_hint(tag_names)
        if hint:
            lines.append(hint + "\n")
        mapped += 1
    if notes:
        lines.append("\n")
        lines.extend(f"{TODO_COMMENT}{note}\n" for note in notes)
    return "".join(lines), notes, mapped


def migrate_config(paths, case_id_marker: str = "test_case_id") -> ConfigMigration | None:
    """None when no qualifying pyproject.toml exists; a skipped
    ConfigMigration when a ctrlrunner.toml already sits next to it."""
    source = find_pyproject(paths)
    if source is None:
        return None
    target = source.parent / "ctrlrunner.toml"
    if target.exists():
        return ConfigMigration(
            source=source,
            target=target,
            text=None,
            skipped_reason=(
                f"{target} already exists -- not overwritten; merge options "
                f"from {source} manually if needed"
            ),
        )
    data = tomllib.loads(source.read_text(encoding="utf-8"))
    ini_options = data.get("tool", {}).get("pytest", {}).get("ini_options", {})
    text, notes, mapped = build_ctrlrunner_toml(ini_options, case_id_marker)
    return ConfigMigration(source=source, target=target, text=text, notes=notes, mapped=mapped)
